"""added photo_id column to Products table

Revision ID: 12af9bcacd8f
Revises: a8e6117ba593
Create Date: 2022-09-29 15:09:57.274315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12af9bcacd8f'
down_revision = 'a8e6117ba593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo_id')
    # ### end Alembic commands ###
