"""added currency column in the Purchase model

Revision ID: 5de8b871a180
Revises: ed1cc5537f87
Create Date: 2022-10-25 17:04:47.751676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de8b871a180'
down_revision = 'ed1cc5537f87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('currency', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'currency')
    # ### end Alembic commands ###
