"""new corrected columns in payment tables

Revision ID: 9a73d745c879
Revises: e994d529e61c
Create Date: 2022-10-27 15:32:47.258592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a73d745c879'
down_revision = 'e994d529e61c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('btc_payments', sa.Column('transaction_key', sa.String(), nullable=True))
    op.drop_constraint('btc_payments_transaction_hash_key', 'btc_payments', type_='unique')
    op.create_unique_constraint(None, 'btc_payments', ['transaction_key'])
    op.drop_column('btc_payments', 'transaction_hash')
    op.add_column('eth_payments', sa.Column('transaction_hash', sa.String(), nullable=True))
    op.drop_constraint('eth_payments_transaction_key_key', 'eth_payments', type_='unique')
    op.create_unique_constraint(None, 'eth_payments', ['transaction_hash'])
    op.drop_column('eth_payments', 'transaction_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_payments', sa.Column('transaction_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'eth_payments', type_='unique')
    op.create_unique_constraint('eth_payments_transaction_key_key', 'eth_payments', ['transaction_key'])
    op.drop_column('eth_payments', 'transaction_hash')
    op.add_column('btc_payments', sa.Column('transaction_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'btc_payments', type_='unique')
    op.create_unique_constraint('btc_payments_transaction_hash_key', 'btc_payments', ['transaction_hash'])
    op.drop_column('btc_payments', 'transaction_key')
    # ### end Alembic commands ###
