"""user_id columns now have BigInteger() type

Revision ID: ed1cc5537f87
Revises: 4b4df4551c95
Create Date: 2022-10-11 16:47:59.480933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1cc5537f87'
down_revision = '4b4df4551c95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'purchases', 'customers', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    # ### end Alembic commands ###
